//*****************************************************************************
//*****************************************************************************
//  FILENAME:  ADCINCVR_3.h
//  Version: 3.1, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  ADCINCVR User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8C.h>

//-------------------------------------------------
// Defines for ADCINCVR_3 API's.
//-------------------------------------------------

// Power Setting Constants
#define ADCINCVR_3_OFF            0
#define ADCINCVR_3_LOWPOWER       1
#define ADCINCVR_3_MEDPOWER       2
#define ADCINCVR_3_HIGHPOWER      3

// Function Fastcall Pragmas
#pragma fastcall16 ADCINCVR_3_Start
#pragma fastcall16 ADCINCVR_3_SetPower
#pragma fastcall16 ADCINCVR_3_GetSamples
#pragma fastcall16 ADCINCVR_3_StopAD
#pragma fastcall16 ADCINCVR_3_Stop
#pragma fastcall16 ADCINCVR_3_fIsData
#pragma fastcall16 ADCINCVR_3_fIsDataAvailable
#pragma fastcall16 ADCINCVR_3_iGetData
#pragma fastcall16 ADCINCVR_3_iGetDataClearFlag
#pragma fastcall16 ADCINCVR_3_ClearFlag
#pragma fastcall16 ADCINCVR_3_SetResolution

//-------------------------------------------------
// Prototypes of the ADCINCVR_3 API.
//-------------------------------------------------

extern void ADCINCVR_3_Start(BYTE bPower);
extern void ADCINCVR_3_SetPower(BYTE bPower);
extern void ADCINCVR_3_GetSamples(BYTE bNumSamples);
extern void ADCINCVR_3_StopAD(void);
extern void ADCINCVR_3_Stop(void);
extern CHAR ADCINCVR_3_fIsData(void);
extern CHAR ADCINCVR_3_fIsDataAvailable(void);
extern INT  ADCINCVR_3_iGetData(void);
extern INT  ADCINCVR_3_iGetDataClearFlag(void);
extern void ADCINCVR_3_ClearFlag(void);

extern void ADCINCVR_3_SetResolution(BYTE bResolution);

#define ADCINCVR_3_bNUMBITS  0x0d

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------

// Integrator Block Register Definitions
#pragma ioport  ADCINCVR_3_bfAtoDcr0:   0x088
BYTE            ADCINCVR_3_bfAtoDcr0;
#pragma ioport  ADCINCVR_3_bfAtoDcr1:   0x089
BYTE            ADCINCVR_3_bfAtoDcr1;
#pragma ioport  ADCINCVR_3_bfAtoDcr2:   0x08a
BYTE            ADCINCVR_3_bfAtoDcr2;
#pragma ioport  ADCINCVR_3_bfAtoDcr3:   0x08b
BYTE            ADCINCVR_3_bfAtoDcr3;

// Counter Block Register Definitions
#pragma ioport  ADCINCVR_3_fCounterFN:  0x130
BYTE            ADCINCVR_3_fCounterFN;
#pragma ioport  ADCINCVR_3_fCounterSL:  0x131
BYTE            ADCINCVR_3_fCounterSL;
#pragma ioport  ADCINCVR_3_fCounterOS:  0x132
BYTE            ADCINCVR_3_fCounterOS;
#pragma ioport  ADCINCVR_3_bCount:  0x030
BYTE            ADCINCVR_3_bCount;
#pragma ioport  ADCINCVR_3_bPeriod: 0x031
BYTE            ADCINCVR_3_bPeriod;
#pragma ioport  ADCINCVR_3_bCompare:    0x032
BYTE            ADCINCVR_3_bCompare;
#pragma ioport  ADCINCVR_3_bCounter_CR0:    0x033
BYTE            ADCINCVR_3_bCounter_CR0;


// PWM16 Block Register Definitions
#pragma ioport  ADCINCVR_3_bfPWM_LSB_FN:    0x140
BYTE            ADCINCVR_3_bfPWM_LSB_FN;
#pragma ioport  ADCINCVR_3_bfPWM_MSB_FN:    0x144
BYTE            ADCINCVR_3_bfPWM_MSB_FN;
#pragma ioport  ADCINCVR_3_fPWM_LSB_CR0:    0x043
BYTE            ADCINCVR_3_fPWM_LSB_CR0;
#pragma ioport  ADCINCVR_3_fPWM_MSB_CR0:    0x047
BYTE            ADCINCVR_3_fPWM_MSB_CR0;
#pragma ioport  ADCINCVR_3_bPWM_Count_MSB:  0x044
BYTE            ADCINCVR_3_bPWM_Count_MSB;
#pragma ioport  ADCINCVR_3_bPWM_Count_LSB:  0x040
BYTE            ADCINCVR_3_bPWM_Count_LSB;
#pragma ioport  ADCINCVR_3_bPWM_Period_MSB: 0x045
BYTE            ADCINCVR_3_bPWM_Period_MSB;
#pragma ioport  ADCINCVR_3_bPWM_Period_LSB: 0x041
BYTE            ADCINCVR_3_bPWM_Period_LSB;
#pragma ioport  ADCINCVR_3_bPWM_IntTime_MSB:    0x046
BYTE            ADCINCVR_3_bPWM_IntTime_MSB;
#pragma ioport  ADCINCVR_3_bPWM_IntTime_LSB:    0x042
BYTE            ADCINCVR_3_bPWM_IntTime_LSB;
#pragma ioport  ADCINCVR_3_bfPWM_LSB_FN:    0x140
BYTE            ADCINCVR_3_bfPWM_LSB_FN;
#pragma ioport  ADCINCVR_3_bfPWM_MSB_FN:    0x144
BYTE            ADCINCVR_3_bfPWM_MSB_FN;

// end of file ADCINCVR_3.h
