//*****************************************************************************
//*****************************************************************************
//  FILENAME:  ADCINCVR_4.h
//  Version: 3.1, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  ADCINCVR User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8C.h>

//-------------------------------------------------
// Defines for ADCINCVR_4 API's.
//-------------------------------------------------

// Power Setting Constants
#define ADCINCVR_4_OFF            0
#define ADCINCVR_4_LOWPOWER       1
#define ADCINCVR_4_MEDPOWER       2
#define ADCINCVR_4_HIGHPOWER      3

// Function Fastcall Pragmas
#pragma fastcall16 ADCINCVR_4_Start
#pragma fastcall16 ADCINCVR_4_SetPower
#pragma fastcall16 ADCINCVR_4_GetSamples
#pragma fastcall16 ADCINCVR_4_StopAD
#pragma fastcall16 ADCINCVR_4_Stop
#pragma fastcall16 ADCINCVR_4_fIsData
#pragma fastcall16 ADCINCVR_4_fIsDataAvailable
#pragma fastcall16 ADCINCVR_4_iGetData
#pragma fastcall16 ADCINCVR_4_iGetDataClearFlag
#pragma fastcall16 ADCINCVR_4_ClearFlag
#pragma fastcall16 ADCINCVR_4_SetResolution

//-------------------------------------------------
// Prototypes of the ADCINCVR_4 API.
//-------------------------------------------------

extern void ADCINCVR_4_Start(BYTE bPower);
extern void ADCINCVR_4_SetPower(BYTE bPower);
extern void ADCINCVR_4_GetSamples(BYTE bNumSamples);
extern void ADCINCVR_4_StopAD(void);
extern void ADCINCVR_4_Stop(void);
extern CHAR ADCINCVR_4_fIsData(void);
extern CHAR ADCINCVR_4_fIsDataAvailable(void);
extern INT  ADCINCVR_4_iGetData(void);
extern INT  ADCINCVR_4_iGetDataClearFlag(void);
extern void ADCINCVR_4_ClearFlag(void);

extern void ADCINCVR_4_SetResolution(BYTE bResolution);

#define ADCINCVR_4_bNUMBITS  0x0d

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------

// Integrator Block Register Definitions
#pragma ioport  ADCINCVR_4_bfAtoDcr0:   0x08c
BYTE            ADCINCVR_4_bfAtoDcr0;
#pragma ioport  ADCINCVR_4_bfAtoDcr1:   0x08d
BYTE            ADCINCVR_4_bfAtoDcr1;
#pragma ioport  ADCINCVR_4_bfAtoDcr2:   0x08e
BYTE            ADCINCVR_4_bfAtoDcr2;
#pragma ioport  ADCINCVR_4_bfAtoDcr3:   0x08f
BYTE            ADCINCVR_4_bfAtoDcr3;

// Counter Block Register Definitions
#pragma ioport  ADCINCVR_4_fCounterFN:  0x134
BYTE            ADCINCVR_4_fCounterFN;
#pragma ioport  ADCINCVR_4_fCounterSL:  0x135
BYTE            ADCINCVR_4_fCounterSL;
#pragma ioport  ADCINCVR_4_fCounterOS:  0x136
BYTE            ADCINCVR_4_fCounterOS;
#pragma ioport  ADCINCVR_4_bCount:  0x034
BYTE            ADCINCVR_4_bCount;
#pragma ioport  ADCINCVR_4_bPeriod: 0x035
BYTE            ADCINCVR_4_bPeriod;
#pragma ioport  ADCINCVR_4_bCompare:    0x036
BYTE            ADCINCVR_4_bCompare;
#pragma ioport  ADCINCVR_4_bCounter_CR0:    0x037
BYTE            ADCINCVR_4_bCounter_CR0;


// PWM16 Block Register Definitions
#pragma ioport  ADCINCVR_4_bfPWM_LSB_FN:    0x148
BYTE            ADCINCVR_4_bfPWM_LSB_FN;
#pragma ioport  ADCINCVR_4_bfPWM_MSB_FN:    0x14c
BYTE            ADCINCVR_4_bfPWM_MSB_FN;
#pragma ioport  ADCINCVR_4_fPWM_LSB_CR0:    0x04b
BYTE            ADCINCVR_4_fPWM_LSB_CR0;
#pragma ioport  ADCINCVR_4_fPWM_MSB_CR0:    0x04f
BYTE            ADCINCVR_4_fPWM_MSB_CR0;
#pragma ioport  ADCINCVR_4_bPWM_Count_MSB:  0x04c
BYTE            ADCINCVR_4_bPWM_Count_MSB;
#pragma ioport  ADCINCVR_4_bPWM_Count_LSB:  0x048
BYTE            ADCINCVR_4_bPWM_Count_LSB;
#pragma ioport  ADCINCVR_4_bPWM_Period_MSB: 0x04d
BYTE            ADCINCVR_4_bPWM_Period_MSB;
#pragma ioport  ADCINCVR_4_bPWM_Period_LSB: 0x049
BYTE            ADCINCVR_4_bPWM_Period_LSB;
#pragma ioport  ADCINCVR_4_bPWM_IntTime_MSB:    0x04e
BYTE            ADCINCVR_4_bPWM_IntTime_MSB;
#pragma ioport  ADCINCVR_4_bPWM_IntTime_LSB:    0x04a
BYTE            ADCINCVR_4_bPWM_IntTime_LSB;
#pragma ioport  ADCINCVR_4_bfPWM_LSB_FN:    0x148
BYTE            ADCINCVR_4_bfPWM_LSB_FN;
#pragma ioport  ADCINCVR_4_bfPWM_MSB_FN:    0x14c
BYTE            ADCINCVR_4_bfPWM_MSB_FN;

// end of file ADCINCVR_4.h
