//*****************************************************************************
//*****************************************************************************
//  FILENAME:  AMUX4.h
//  Version: 1.4, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  AMux4 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


#include <m8c.h>
//-------------------------------------------------
// Defines for AMUX4 API's.
//-------------------------------------------------
#define AMUX4_PORT0_0                  0x00
#define AMUX4_PORT0_2                  0x01
#define AMUX4_PORT0_4                  0x02
#define AMUX4_PORT0_6                  0x03

#define AMUX4_PORT0_1                  0x00
#define AMUX4_PORT0_3                  0x01
#define AMUX4_PORT0_5                  0x02
#define AMUX4_PORT0_7                  0x03


#pragma fastcall16 AMUX4_InputSelect
#pragma fastcall16 AMUX4_Start
#pragma fastcall16 AMUX4_Stop

//-------------------------------------------------
// Prototypes of the AMUX4 API.
//-------------------------------------------------

extern void AMUX4_InputSelect(BYTE bChannel);
extern void AMUX4_Start(void);
extern void AMUX4_Stop(void);

// end of file AMUX4.h
