/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "ADCINC.h"
#include "AMUX4.h"
#include "I2CHWCommon.h"
#include "I2CHWSlave.h"
#include "PGA_1.h"
#include "TX8.h"
#include "Timer16.h"

#endif
