/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "ADCINCVR_1.h"
#include "ADCINCVR_2.h"
#include "ADCINCVR_3.h"
#include "ADCINCVR_4.h"
#include "I2CHWCommon.h"
#include "I2CHWSlave.h"
#include "PGA_1.h"
#include "PGA_2.h"
#include "PGA_3.h"
#include "PGA_4.h"
#include "TX8.h"
#include "Timer16_1.h"

#endif
